name: CI # Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features --workspace

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish dry run
        run: cargo publish --dry-run
