name: Release

on:
  push:
    tags:
      - v1*
  workflow_dispatch:

jobs:
  publish:
    name: Publishing for ${{ matrix.job.build }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - build: macos
            os: macos-latest
            os-name: macos
            target: x86_64-apple-darwin
            use-cross: false

          - build: macos m1
            os: macos-latest
            os-name: macos
            target: aarch64-apple-darwin
            use-cross: true

          - build: linux
            os: ubuntu-latest
            os-name: linux
            target: x86_64-unknown-linux-gnu
            use-cross: false

          - build: linux-arm
            os: ubuntu-latest
            os-name: linux
            target: aarch64-unknown-linux-gnu
            use-cross: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Install aarch64 deps
        if: matrix.job.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt update
          sudo apt-get install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: Cargo build
        run: cargo build --release --target ${{ matrix.job.target }}

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release

          RELEASE_NAME=mob-${GITHUB_REF/refs\/tags\//}-${{ matrix.job.os-name }}-${{ matrix.job.target }}
          tar czvf $RELEASE_NAME.tar.gz mob
          shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            target/${{ matrix.job.target }}/release/mob-*.tar.gz
            target/${{ matrix.job.target }}/release/mob-*.sha256

  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token ${{ secrets.CARGO_API_KEY }}

  homebrew:
    name: Bump Homebrew formula
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Bumb homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2.1
        if: "!contains(github.ref, '-')"
        with:
          formula-name: mob
          homebrew-tap: afajl/homebrew-mob
          download-url: 'https://github.com/afajl/mob/releases/download/${{ steps.extract-version.outputs.tag-name }}/mob-${{ steps.extract-version.outputs.tag-name }}-macos-x86_64-apple-darwin.tar.gz'
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
