name: Release

on:
  push:
    tags:
      - v1*
  workflow_dispatch:


jobs:
  publish:
    name: Publishing for ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - build: macos
            os: macos-latest
            os-name: macos
            target: x86_64-apple-darwin
            architecture: x86_64
            use-cross: false

          - build: linux
            os: ubuntu-latest
            os-name: linux
            target: x86_64-unknown-linux-gnu
            architecture: x86_64
            use-cross: false

          - build: linux-arm
            os: ubuntu-latest
            os-name: linux
            target: aarch64-unknown-linux-gnu
            architecture: arm64
            use-cross: true

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          toolchain: stable
          args: --release --target ${{ matrix.job.target }}

      - name: Strip release binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.job.target }}/release/mob"

      - name: Strip release binary (arm)
        if: matrix.build == 'linux-arm'
        run: |
          sudo apt update
          sudo apt-get install -y binutils-aarch64-linux-gnu
          aarch64-linux-gnu-strip "target/${{ matrix.job.target }}/release/mob"

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.job.target }}/release

          RELEASE_NAME=mob-${GITHUB_REF/refs\/tags\//}-${{ matrix.job.os-name }}-${{ matrix.job.target }}
          tar czvf $RELEASE_NAME.tar.gz mob
          shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            target/${{ matrix.job.target }}/release/mob-*.tar.gz
            target/${{ matrix.job.target }}/release/mob-*.sha256

  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }}
